### ISSUE TITLE
Students should be able to log in using the account their parent set up.

### ISSUE THREAD

**Issue by briananstett** [briananstett/SeniorCapstone#17]

**Comment by mattjschmidt** [comment]
Adding a Sign In option at the Log In page to supply this functionality

**Comment by mattjschmidt** [comment]
All thats left is to create a redirect to a new form for sign in to a local account.

**Comment by briananstett** [comment]
Hey @mattjschmidt, does this include all the back end stuff? 
after a student gets redirected to the login page and they enter their credentials, the following has to happen.

1. Check if there's a username with that provided password
2. If there is, create a session variable
3. Redirect the student to their home page(which I guess would the dashboard?)



Also some things to consider, parents will always have Google accounts, with students it could vary. So if we are having a separate forms for parents and students, we'll have to make sure there's a way for a student to go through the normal Google Oauth process (like a parent account) to log in with their Google account.
